services:
  glacier-backend:
    build: ./glacier-backend
    command:
      - "bash -c python server.py"
    ports:
      - "8888:8888"
    environment:
      - DB_HOST=glacierrender-postgres-1
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=lolava
    networks:
      - backbone
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=lolava
    networks:
      - backbone

networks:
  backbone:
    name: backbone
