services:
  backend:
    build: ./glacier-backend
    ports:
      - "8888:8888"
    environment:
      - DB_HOST=glacierrender-postgres-1
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=lolava
      - UPLOAD_FACILITY=/tmp
    networks:
      - glacier-backbone
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=lolava
    networks:
      - glacier-backbone

networks:
  glacier-backbone:
    name: glacier-backbone
